INSERT INTO QUALIFICATIONS (QUALIFICATION_ID, QUALIFICATION_CODE, QUALIFICATION_DESC) VALUES ('1', 'SEC-45', 'Secretarial work; candidate must type at least 45 words per minute');
INSERT INTO QUALIFICATIONS (QUALIFICATION_ID, QUALIFICATION_CODE, QUALIFICATION_DESC) VALUES ('2', 'SEC-60', 'Secretarial work; candidate must type at least 60 words per minute');
INSERT INTO QUALIFICATIONS (QUALIFICATION_ID, QUALIFICATION_CODE, QUALIFICATION_DESC) VALUES ('3', 'CLERK', 'General clerking work');
INSERT INTO QUALIFICATIONS (QUALIFICATION_ID, QUALIFICATION_CODE, QUALIFICATION_DESC) VALUES ('4', 'PRG-PY', 'Programmer, Python');
INSERT INTO QUALIFICATIONS (QUALIFICATION_ID, QUALIFICATION_CODE, QUALIFICATION_DESC) VALUES ('5', 'PRG-C++', 'Programmer, C++');
INSERT INTO QUALIFICATIONS (QUALIFICATION_ID, QUALIFICATION_CODE, QUALIFICATION_DESC) VALUES ('6', 'DBA-ORA', 'Database Administrator, Oracle');
INSERT INTO QUALIFICATIONS (QUALIFICATION_ID, QUALIFICATION_CODE, QUALIFICATION_DESC) VALUES ('7', 'DBA-DB2', 'Database Administrator, IBM DB2');
INSERT INTO QUALIFICATIONS (QUALIFICATION_ID, QUALIFICATION_CODE, QUALIFICATION_DESC) VALUES ('8', 'DBA-SQLSERV', 'Database Administrator, MS SQL Server');
INSERT INTO QUALIFICATIONS (QUALIFICATION_ID, QUALIFICATION_CODE, QUALIFICATION_DESC) VALUES ('9', 'SYS-1', 'Systems Analyst, level 1');
INSERT INTO QUALIFICATIONS (QUALIFICATION_ID, QUALIFICATION_CODE, QUALIFICATION_DESC) VALUES ('10', 'SYS-2', 'Systems Analyst, level 2');
INSERT INTO QUALIFICATIONS (QUALIFICATION_ID, QUALIFICATION_CODE, QUALIFICATION_DESC) VALUES ('11', 'NW-CIS', 'Network Administrator, Cisco experience');
INSERT INTO QUALIFICATIONS (QUALIFICATION_ID, QUALIFICATION_CODE, QUALIFICATION_DESC) VALUES ('12', 'WD-CF', 'Web Developer, ColdFusion');



INSERT INTO qualification_status (QUALIFICATION_ID, CANDIDATE_ID) VALUES ((SELECT QUALIFICATION_ID FROM qualifications WHERE QUALIFICATION_ID = '9'), (SELECT CANDIDATE_ID FROM candidate));

=================================================================================================================
*statements to fill out opening table*

INSERT INTO opening 
VALUES (1, (SELECT COMPANY_ID FROM COMPANY WHERE COMPANY_ID = 1), 
(SELECT QUALIFICATION_ID FROM QUALIFICATIONS WHERE QUALIFICATION_ID = 1), 02/15/2023, 06/07/2024, 23.15);

INSERT INTO opening 
VALUES (2, (SELECT COMPANY_ID FROM COMPANY WHERE COMPANY_ID = 2), 
(SELECT QUALIFICATION_ID FROM QUALIFICATIONS WHERE QUALIFICATION_ID = 2), 03/15/2023, 07/07/2024, 30.15);

INSERT INTO opening 
VALUES (3, (SELECT COMPANY_ID FROM COMPANY WHERE COMPANY_ID = 3), 
(SELECT QUALIFICATION_ID FROM QUALIFICATIONS WHERE QUALIFICATION_ID = 3), 01/15/2023, 09/07/2024, 26.05);

INSERT INTO opening 
VALUES (4, (SELECT COMPANY_ID FROM COMPANY WHERE COMPANY_ID = 4), 
(SELECT QUALIFICATION_ID FROM QUALIFICATIONS WHERE QUALIFICATION_ID = 4), 06/15/2023, 02/07/2024, 40.00);

INSERT INTO opening 
VALUES (5, (SELECT COMPANY_ID FROM COMPANY WHERE COMPANY_ID = 5), 
(SELECT QUALIFICATION_ID FROM QUALIFICATIONS WHERE QUALIFICATION_ID = 5), 02/22/2023, 06/26/2024, 45.23);

INSERT INTO opening 
VALUES (6, (SELECT COMPANY_ID FROM COMPANY WHERE COMPANY_ID = 6), 
(SELECT QUALIFICATION_ID FROM QUALIFICATIONS WHERE QUALIFICATION_ID = 6), 07/15/2023, 07/07/2024, 23.35);

INSERT INTO opening 
VALUES (7, (SELECT COMPANY_ID FROM COMPANY WHERE COMPANY_ID = 7), 
(SELECT QUALIFICATION_ID FROM QUALIFICATIONS WHERE QUALIFICATION_ID = 7), 04/15/2023, 03/07/2024, 32.15);

=================================================================================================================
*Sql statements to fill out company table*

INSERT INTO COMPANY
VALUES (1, 'Facebook');

INSERT INTO COMPANY
VALUES (2, 'Google');

INSERT INTO COMPANY
VALUES (3, 'Walmart');

INSERT INTO COMPANY
VALUES (4, 'Microsoft');

INSERT INTO COMPANY
VALUES (5, 'Apple');

INSERT INTO COMPANY
VALUES (6, 'UPS');

INSERT INTO COMPANY
VALUES (7, 'FedEx');
