INSERT INTO QUALIFICATIONS (QUALIFICATION_ID, QUALIFICATION_CODE, QUALIFICATION_DESC) VALUES ('1', 'SEC-45', 'Secretarial work; candidate must type at least 45 words per minute');
INSERT INTO QUALIFICATIONS (QUALIFICATION_ID, QUALIFICATION_CODE, QUALIFICATION_DESC) VALUES ('2', 'SEC-60', 'Secretarial work; candidate must type at least 60 words per minute');
INSERT INTO QUALIFICATIONS (QUALIFICATION_ID, QUALIFICATION_CODE, QUALIFICATION_DESC) VALUES ('3', 'CLERK', 'General clerking work');
INSERT INTO QUALIFICATIONS (QUALIFICATION_ID, QUALIFICATION_CODE, QUALIFICATION_DESC) VALUES ('4', 'PRG-PY', 'Programmer, Python');
INSERT INTO QUALIFICATIONS (QUALIFICATION_ID, QUALIFICATION_CODE, QUALIFICATION_DESC) VALUES ('5', 'PRG-C++', 'Programmer, C++');
INSERT INTO QUALIFICATIONS (QUALIFICATION_ID, QUALIFICATION_CODE, QUALIFICATION_DESC) VALUES ('6', 'DBA-ORA', 'Database Administrator, Oracle');
INSERT INTO QUALIFICATIONS (QUALIFICATION_ID, QUALIFICATION_CODE, QUALIFICATION_DESC) VALUES ('7', 'DBA-DB2', 'Database Administrator, IBM DB2');
INSERT INTO QUALIFICATIONS (QUALIFICATION_ID, QUALIFICATION_CODE, QUALIFICATION_DESC) VALUES ('8', 'DBA-SQLSERV', 'Database Administrator, MS SQL Server');
INSERT INTO QUALIFICATIONS (QUALIFICATION_ID, QUALIFICATION_CODE, QUALIFICATION_DESC) VALUES ('9', 'SYS-1', 'Systems Analyst, level 1');
INSERT INTO QUALIFICATIONS (QUALIFICATION_ID, QUALIFICATION_CODE, QUALIFICATION_DESC) VALUES ('10', 'SYS-2', 'Systems Analyst, level 2');
INSERT INTO QUALIFICATIONS (QUALIFICATION_ID, QUALIFICATION_CODE, QUALIFICATION_DESC) VALUES ('11', 'NW-CIS', 'Network Administrator, Cisco experience');
INSERT INTO QUALIFICATIONS (QUALIFICATION_ID, QUALIFICATION_CODE, QUALIFICATION_DESC) VALUES ('12', 'WD-CF', 'Web Developer, ColdFusion');



INSERT INTO qualification_status (QUALIFICATION_ID, CANDIDATE_ID) VALUES ((SELECT QUALIFICATION_ID FROM qualifications WHERE QUALIFICATION_ID = '9'), (SELECT CANDIDATE_ID FROM candidate));